---
title: North Hills Christian Church
timezone: UTC
collections:
  c2c_programs:
    title: C2C Programs
    output: false
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  sermon_library:
    title: Sermons
    output: false
  groups:
    title: Small Groups
    output: false
  team_members:
    title: Team Members
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sermon_library
  values:
    title: ''
    speaker: ''
    media: ''
    sermon_date: ''
- scope:
    path: ''
    type: team_members
  values:
    role: ''
    bio text: ''
    image: ''
- scope:
    path: ''
    type: events
  values:
    image: ''
    event date: ''
    sign up: ''
- scope:
    path: ''
    type: c2c_programs
  values:
    image: ''
    description: ''
    get involved email: ''
- scope:
    path: ''
    type: groups
  values:
    when: ''
    where: ''
    child care: ''
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
service_time: 10am
